In [2]:
import numpy as np


In [3]:
X = np.array([
    [63,45,233],
    [41,130,204],
    [37,130,250],
    [56,120,236],
    [57,120,236]
])
y = np.array([[1],[1],[1],[0],[0]])

In [4]:
X = X/np.max(X,axis = 0)
np.random.seed(1)
W1 = np.random.rand(3,5)
b1 = np.zeros((1,5))
W2 = np.random.rand(5,1)
b2 = np.zeros((1,1))

In [5]:
lr = 0.5
epoches = 1000

In [6]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))


In [7]:
for i in range(epoches):

    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)

    z2 = np.dot(a1, W2) + b2
    output = sigmoid(z2)

    err = y - output
    d_out = err * output * (1 - output)

    d_hidden = np.dot(d_out, W2.T) * a1 * (1 - a1)

    W2 += lr * np.dot(a1.T, d_out)
    b2 += lr * np.sum(d_out, axis=0, keepdims=True)

    W1 += lr * np.dot(X.T, d_hidden)
    b1 += lr * np.sum(d_hidden, axis=0, keepdims=True)

print(np.round(output,3))


[[0.882]
 [0.811]
 [0.967]
 [0.177]
 [0.142]]


In [8]:
print((output>0.5).astype(int))

[[1]
 [1]
 [1]
 [0]
 [0]]


**Testing**

In [9]:
X_test = np.array([52,136,365])
X_test = X_test/np.max(X_test,axis = 0)

In [10]:
z = np.dot(X_test, W1) + b1
a = sigmoid(z)

z_h = np.dot(a, W2) + b2
output = sigmoid(z_h)

In [11]:
output

array([[0.9999857]])

In [12]:
print((output>0.5).astype(int))

[[1]]
