In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

## AND GATE

In [2]:
X=np.array([(0,0),(0,1),(1,0),(1,1)])
Y=np.array([0,0,0,1])

In [3]:
W=np.zeros(2)
b = -0.5

In [4]:
lr = 1

In [5]:
def activ(x):
    return x>=0

In [6]:
W.shape, X.shape

((2,), (4, 2))

In [7]:
EPOCH=10
for _ in range(EPOCH):
    for i in range(len(X)):
        z=np.dot(X[i],W)+b
        y_pred = activ(z)
        err = Y[i] - y_pred
        W = W + lr*err*X[i]
        b=b+lr*err


print(W)
print(b)

[2. 1.]
-2.5


## SPAM 1

In [8]:
import numpy as np

In [9]:
X = np.array([
    [1,1,1,1],
    [1,0,1,1],
    [0,0,0,0],
    [0,1,0,0]
])

Y= np.array([1,1,0,0])

In [10]:
W=np.zeros(4)
b = -0.5

In [11]:
lr = 1

In [12]:
def activ(x):
    return x>=0

In [13]:
W.shape, X.shape

((4,), (4, 4))

In [14]:
EPOCH=10
for _ in range(EPOCH):
    for i in range(len(X)):
        z=np.dot(X[i],W)+b
        y_pred = activ(z)
        err = Y[i] - y_pred
        W = W + lr*err*X[i]
        b=b+lr*err


print(W)
print(b)

[1. 0. 1. 1.]
-1.5


In [15]:
test = np.array([1,1,0,1])
def test_imp(test):
    z=np.dot(test,W)+b
    y_pred = activ(z)
    # print(y_pred)
    
    if y_pred>0:
        print("Spam")
    else:
        print("Not Spam")

In [16]:
def encode(sent):
    vec = np.zeros(4)
    for i in sent.split():
        # print(i)
        if i.lower() == "free":
            vec[0] = 1
        if i.lower() == "win":
            vec[1] = 1
        if i.lower() == "after":
            vec[2] = 1
        if i.lower() == "click":
            vec[3] = 1
    return vec

In [17]:
# encode("Click to win free")

inp = input("Enter the string: ")
en_vec = encode(inp.strip())
test_imp(en_vec)

Enter the string:  Click to win free


Spam


## Spam 2

In [18]:
import numpy as np

In [19]:
sms = ["Win a free laptop", "call when start game", "class at 10 am","offer to win for free mobile"]

label = ["Spam", "Not Spam", "Not Spam","Spam"]

In [20]:
def encode_label(text):
    if text == "Spam":
        return 1
    else: return 0

In [21]:
def encode(sent):
    vec = np.zeros(4)
    for i in sent.split():
        # print(i)
        if i.lower() == "free":
            vec[0] = 1
        if i.lower() == "win":
            vec[1] = 1
        if i.lower() == "after":
            vec[2] = 1
        if i.lower() == "click":
            vec[3] = 1
    return vec

In [22]:
X = np.array([encode(i) for i in sms])
Y=[]
for i in label:
    Y.append(encode_label(i))
Y = np.array(Y)


In [23]:
X, Y

(array([[1., 1., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 0., 0.]]),
 array([1, 0, 0, 1]))

In [24]:
W=np.zeros(4)
b = -0.5

In [25]:
lr = 1

In [26]:
def activ(x):
    return x>=0

In [27]:
W.shape, X.shape

((4,), (4, 4))

In [28]:
EPOCH=10
for _ in range(EPOCH):
    for i in range(len(X)):
        z=np.dot(X[i],W)+b
        y_pred = activ(z)
        err = Y[i] - y_pred
        W = W + lr*err*X[i]
        b=b+lr*err


print(W)
print(b)

[1. 1. 0. 0.]
-0.5


In [29]:
def test_imp(test):
    z = np.dot(test,W)+b
    y_pred = activ(z)
    if y_pred > 0:
        print("Spam")
    else:
        print("Not Spam")

In [30]:
# encode("Click to win free")

inp = input("Enter the string: ")
en_vec = encode(inp.strip())
test_imp(en_vec)

Enter the string:  Click to win free


Spam


## UCI Spam

In [31]:
import numpy as np
import pandas as pd

In [32]:
def encode_label(text):
    if text == "Spam":
        return 1
    else: return 0


def encode(sent):
    vec = np.zeros(4)
    for i in sent.split():
        # print(i)
        if i.lower() == "free":
            vec[0] = 1
        if i.lower() == "win":
            vec[1] = 1
        if i.lower() == "after":
            vec[2] = 1
        if i.lower() == "click":
            vec[3] = 1
    return vec

In [33]:
path = "/Users/sabyasachiganguli/Desktop/code/college codes/6th sem/Deep Learning/day1/spam.csv"

df_raw = pd.read_csv(path, encoding = 'latin1')
df_raw.head()
raw = df_raw.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],axis=1)

In [34]:
df_raw.loc[19]

v1                                                         spam
v2            England v Macedonia - dont miss the goals/team...
Unnamed: 2                                                  NaN
Unnamed: 3                                                  NaN
Unnamed: 4                                                  NaN
Name: 19, dtype: object

In [40]:
X = np.array([encode(df_raw.loc[i]['v2']) for i in range(len(df_raw))])